<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.1</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.davemuirhead</groupId>
	<artifactId>drone-sim-consumer-j</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>Drone Simulator Consumer - Java</name>
	<description>
		The Drone Sim project (https://github.com/DaveMuirhead/drone_sim) produces 
		a configurable volume of drone status and telemetry messages to MQTT topics.
		This project is a Java consumer of those messages and is just a means of
		refreshing on recent Java LTS features, Spring Integration and possibly other
		tools like ElasticSearch, etc.
	</description>
	<developers>
		<developer>
			<id>davemuirhead</id>
			<name>Dave Muirhead</name>
			<email>dave@brsg.io</email>
		</developer>
	</developers>
	<properties>
		<java.version>21</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-integration</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.integration</groupId>
			<artifactId>spring-integration-mqtt</artifactId>
		</dependency>

		<!--
			spring-integration-mqtt uses the Eclipse Paho MQTT client which,
			starting in v6.5 made the org.eclipse.paho:org.eclipse.paho.client.mqttv3
			dependency optional, so have to add it explicitly.
		-->
		<dependency>
			<groupId>org.eclipse.paho</groupId>
			<artifactId>org.eclipse.paho.client.mqttv3</artifactId>
			<version>1.2.5</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>